name: Bug Report
description:  Report a bug in HexHive
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen and steps to reproduce the bug?
      placeholder: Tell us what you see.
    validations:
      required: true
    
